---
## Aurora/PG Database Activity Streams Walkthrough
## Main Stack which creates VPC, Cloud9 and Aurora PostgreSQL Cluster
##
## Changelog:
##
## Dependencies:
## none
##
## This sample code is made available under the MIT-0 license. See the LICENSE file.

AWSTemplateFormatVersion: 2010-09-09
Description: Aurora/PG Database Activity Streams Walkthrough

## Parameters
Parameters:
  # EnvType:
  #   Type: String
  #   Default: dev
  #   AllowedValues:
  #     - prod
  #     - dev
  #   Description: Determines if we are in EE or not
  C9EC2InstanceType:
    Description: EC2 instance type on which IDE runs
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - m5.large
  C9AutoHibernateTimeout:
    Description: How many minutes idle before shutting down the IDE. Options, 30min, 1hr, 4hr, 1day, 1week, Never (0)
    Type: Number
    Default: 240
    AllowedValues:
      - 30
      - 60
      - 240
      - 1440
      - 10080
      - 0
  TemplateName:
    Type: String
    Description: Name used for different elements created.
  PubSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID of a Public Subnet for Cloud9.

## Conditions
# Conditions:
#   isInEE:
#     !Equals [ !Ref EnvType, "prod" ]
#   isNotInEE:
#     !Equals [ !Ref EnvType, "dev" ]

Resources:
  Cloud9Instance:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: !Sub ${TemplateName}-Cloud9-IDE
      Description: !Sub ${TemplateName}-Cloud9-IDE
      AutomaticStopTimeMinutes: !Ref C9AutoHibernateTimeout
      SubnetId: !Ref PubSubnetId
      InstanceType: !Ref C9EC2InstanceType
      OwnerArn:
        # !If [isInEE, !Sub 'arn:aws:sts::${AWS::AccountId}:assumed-role/TeamRole/MasterKey', !Ref "AWS::NoValue"]
        # !Sub 'arn:aws:sts::${AWS::AccountId}:assumed-role/TeamRole/MasterKey'
        # Creator owns the Cloud9 env
        !Ref "AWS::NoValue"

## Outputs
Outputs:
  Cloud9URL:
    Description: Aurora Postgres Labs Cloud9 Environment
    Value:
      Fn::Join:
      - ''
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
        - !Ref Cloud9Instance
