---
## Amazon Aurora PostgreSQL Database Activity Walktrough
## Creates the resources for reporting
##
## Changelog:
##
## Dependencies:
## none
##
## This sample code is made available under the MIT-0 license. See the LICENSE file.

AWSTemplateFormatVersion: 2010-09-09
Description: Aurora/PG Database Activity Streams Walkthrough

## Parameters
Parameters:
  TemplateName:
    Type: String
    Description: Name used for different elements created.
  
  S3BucketARN:
    Type: String
    Description: ARN for the DAS data bucket

  S3BucketPath:
    Type: String
    Description: Path in the S3 bucket

Resources:

# Role for the Glue Crawler
  dasblogCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${TemplateName}-crawler-role-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: GlueS3Access
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - glue:*
                - iam:ListRolePolicies
                - iam:GetRole
                - iam:GetRolePolicy
              Resource: 
                - '*'
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetObject
              Resource:
                -  !Sub ${S3BucketARN}*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 'arn:aws:logs:*:*:/aws-glue/*'

# Query database managed with crawler
  daseventDatabase:
      Type: AWS::Glue::Database
      Properties:
        DatabaseInput:
          Description: 'Metastore for the DAS events'
          Name: !Sub ${TemplateName}-db
        CatalogId: !Ref AWS::AccountId

# Crawler setup for Glue
  gluecrawlerDASEvents:
    Type: AWS::Glue::Crawler
    Description: Used for crawling the Aurora DAS data
    DependsOn:
      - dasblogCrawlerRole
      - daseventDatabase
    Properties:
      Description: Used for crawling the Aurora DAS data
      Name: !Sub ${TemplateName}-crawler
      DatabaseName: !Ref daseventDatabase
      # Role: !GetAtt dasblogCrawlerRole.Arn
      Role: !Ref dasblogCrawlerRole
      Targets:
        S3Targets:
          - Path: { Ref: S3BucketPath }

# Athena Workgroup configuration
  dasblogAthenaWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties: 
      Name: dasblog-workgroup
      RecursiveDeleteOption: "true"
      State: ENABLED
      WorkGroupConfiguration:
        ResultConfiguration: 
          OutputLocation: !Sub s3://${DASAthenaResultsQueryBucket}

# S3 bucket for Athena results
  DASAthenaResultsQueryBucket:
      Type: "AWS::S3::Bucket"
      DeletionPolicy: Delete

# Outputs
Outputs:
  AthenaResultQueryBucket:
    Description: Bucket for managing Athena queries
    Value: !Ref 'DASAthenaResultsQueryBucket'
  DasblogCrawlerRoleArn:
    Description: Role for the web crawler
    Value: !GetAtt dasblogCrawlerRole.Arn
