---
## Amazon Aurora PostgreSQL Database Activity Walktrough
## Creates Aurora PostgreSQL Cluster
##
## Changelog:
##
## Dependencies:
## none
##
## This sample code is made available under the MIT-0 license. See the LICENSE file.
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon RDS PostgreSQL Database Activity Streams Lab
## Parameters
Parameters:
  TemplateName:
    Type: String
    Description: Name used for different elements created.

Resources:
  dasblogCMK:
    Type: AWS::KMS::Key
    DependsOn: roleLambdaFormatter
    Properties:
      Description: Used for DAS event data encryption/decryption
      EnableKeyRotation: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  -
                    - "arn:aws:iam::"
                    - Ref: "AWS::AccountId"
                    - ":root"
            Action: "kms:*"
            Resource: "*"
          - Sid: 'Allow Lambda to use key'
            Effect: Allow
            Action:
              - kms:*
            Principal:
              AWS:
                - !GetAtt 'roleLambdaFormatter.Arn'  
          

  dasblogCMKAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${TemplateName}-cmk-alias
      TargetKeyId: 
        Ref: dasblogCMK

  roleLambdaFormatter:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${TemplateName}-lambda-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser


Outputs:
  LambdaRoleArn:
    Description: 'This is the role used by Lambda function'
    Value: !GetAtt 'roleLambdaFormatter.Arn'  
  
  CMKArn:
    Description: 'Arn for the Key used for encryption/decryption'
    Value: !GetAtt 'dasblogCMK.Arn'  

  CMKKeyID:
    Description: 'Key ID for the Key used for encryption/decryption'
    Value:
      Ref: dasblogCMK